collections:
  projects:
    output: true
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://rtyocum.dev"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: development

author: "Ryan Yocum"
social:
  name: "Ryan Yocum"
  links:
    - https://www.linkedin.com/in/ryan-yocum
    - https://github.com/rtyocum
